dist: xenial
language: python
python:
- "3.5"
- "3.6"
- "3.7"

env:
- TRAVIS_NODE_VERSION="10"

install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install -g mjml
- pip install tox-travis coveralls

script:
- tox

after_success:
- test $TRAVIS_PYTHON_VERSION = "3.7" && coveralls
