# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemodel',
            old_name='template',
            new_name='body',
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
