# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='layout',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 11, 5, 42, 12, 237359, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='happymailer.TemplateModel'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
