# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='layout',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='happymailer.TemplateModel'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
