# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0002_auto_20160530_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
