# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0003_auto_20160530_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
