# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happymailer', '0004_templatemodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='layout',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
